# This file contains Kucoin constants

# USDT Symbols
AVA_USDT = "AVAUSDT"
MTV_USDT = "MTVUSDT"
KMD_USDT = "KMDUSDT"
BTC_USDT = "BTCUSDT"
LYM_USDT = "LYMUSDT"
SNX_USDT = "SNXUSDT"
ETC_USDT = "ETCUSDT"
XLM_USDT = "XLMUSDT"
LTC_USDT = "LTCUSDT"
KCS_USDT = "KCSUSDT"

# USDC Symbols
XRP_USDC = "XRPUSDC"
BCH_USDC = "BCHUSDC"
EOS_USDC = "EOSUSDC"
ADA_USDC = "ADAUSDC"
DOGE_USDC = "DOGEUSDC"
TXA_USDC = "TXAUSDC"
APE_USDC = "APEUSDC"
XCN_USDC = "XCNUSDC"
ETH_USDC = "ETHUSDC"
TRX_USDC = "TRXUSDC"

CURR_ARR = [
    AVA_USDT,
    MTV_USDT,
    KMD_USDT,
    BTC_USDT,
    LYM_USDT,
    SNX_USDT,
    ETC_USDT,
    XLM_USDT,
    LTC_USDT,
    KCS_USDT,
    XRP_USDC,
    BCH_USDC,
    EOS_USDC,
    ADA_USDC,
    DOGE_USDC,
    TXA_USDC,
    APE_USDC,
    XCN_USDC,
    ETH_USDC,
    TRX_USDC
]