# This file contains Kucoin constants

# Token
TOKEN = "2neAiuYvAU61ZDXANAGAsiL4-iAExhsBXZxftpOeh_55i3Ysy2q2LEsEWU64mdzUOPusi34M_wGoSf7iNyEWJ3Tw8Jn4ipO1KvYYOLhUkSL5RzS52v26A9iYB9J6i9GjsxUuhPw3BlrzazF6ghq4L4I7X2JJRjIXh9Lzsfngb6k=.HtKnNVbeikowLI0b5laYnw=="

# URI
MARKET_KLINES = 'wss://ws-api-spot.kucoin.com/market/candles:'

# USDT Symbols
AVA_USDT = "AVA-USDT"
MTV_USDT = "MTV-USDT"
KMD_USDT = "KMD-USDT"
BTC_USDT = "BTC-USDT"
LYM_USDT = "LYM-USDT"
SNX_USDT = "SNX-USDT"
ETC_USDT = "ETC-USDT"
XLM_USDT = "XLM-USDT"
LTC_USDT = "LTC-USDT"
KCS_USDT = "KCS-USDT"

# USDC Symbols
XRP_USDC = "XRP-USDC"
BCH_USDC = "BCH-USDC"
EOS_USDC = "EOS-USDC"
ADA_USDC = "ADA-USDC"
DOGE_USDC = "DOGE-USDC"
TXA_USDC = "TXA-USDC"
APE_USDC = "APE-USDC"
XCN_USDC = "XCN-USDC"
ETH_USDC = "ETH-USDC"
TRX_USDC = "TRX-USDC"

CURR_ARR = [
    AVA_USDT,
    MTV_USDT,
    KMD_USDT,
    BTC_USDT,
    LYM_USDT,
    SNX_USDT,
    ETC_USDT,
    XLM_USDT,
    LTC_USDT,
    KCS_USDT,
    XRP_USDC,
    BCH_USDC,
    EOS_USDC,
    ADA_USDC,
    DOGE_USDC,
    TXA_USDC,
    APE_USDC,
    XCN_USDC,
    ETH_USDC,
    TRX_USDC
]
